### ISSUE TITLE
Particle ID not consistent during playback

### ISSUE THREAD

**Issue by zeekindustries** [keijiro/HdrpVatExample#1]
Hey Keijiro!

Thanks a lot for the reference, it was a great tool to fiddle around and understand how the VAT workflow will be within Unity.

I was trying to achieve an effect where every particle will have a different sprite on an Atlas based on the particle ID, but found out that the particle ID will suddenly swap (in the case of the lava example is every 1/3 of the playback). Any help would be greatly appreciated!

Cheers!

**Comment by keijiro** [comment]
Just for clarification, are you using my ""Set VAT Attributes" block?

**Comment by zeekindustries** [comment]
Yes, that is correct, I tried the latest commit

**Comment by keijiro** [comment]
Thanks for the quick reply. I found an issue in texture coordinates generation and fixed it. Please retry with the latest version.

**Comment by zeekindustries** [comment]
Hey Keijiro!

Thanks a lot for the quick action, just confirmed that it's working as intended.
Really appreciate it, cheers!
