### ISSUE TITLE
Creating texture from Houdini

### ISSUE THREAD

**Issue by getarobo** [keijiro/HdrpVatExample#15]
Hi! 

First of all do appreciate Hdrp integration of Vat :)

I am trying to create VAT textures based on your Houdini file but seems to be some error when I try to open hip file.
![vat_error](https://user-images.githubusercontent.com/997048/132803280-5ef57789-ad55-4f43-9061-862819773e3d.jpg)

if I ignore those and render all via Houdini vat, animation goes wrong(positions seems wrong)
![difference](https://user-images.githubusercontent.com/997048/132803776-52d2da6d-bb3d-454b-898e-9c39786bd2c1.jpg)

Am using Houdini Indie 18.5.672 at the moment. 
Would you be able to help on how to create vat textures from Houdini? or version you used to create example textures?

Thank you so very much :)

**Comment by keijiro** [comment]
Sorry, I can't fix the problem because my Houdini license expired.

I created it about two years ago. The version might be way older than yours. I think you have to create your own asset from scratch.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by getarobo** [comment]
Just for follow up, this is how I got working
1. Install Houdini 18.0.348 
2. Install sidefx Lab: 348(local)
3. click vertex_animation_texture1 from out
4. DO NOT CLICK "Initialize for Engine"<------- very important, some how this breaks everything

FYI,  I am using unity 2020.3.20f1, with DOTS and spawning VAT mesh as entity and it works great :) super performant!
