### ISSUE TITLE
would this example work in gamma space?

### ISSUE THREAD

**Issue by sebas77** [keijiro/HdrpVatExample#16]
as far as I know, unity changes the data in all 16bit formats regardless the srgb check

**Comment by keijiro** [comment]
I don't think it works because it's not about the precision but applying a special non-linear curve.

**Comment by sebas77** [comment]
all right thanks, I suspect the srgb unchecked would keep the textures linear in HDRP, but not in URP. Same reason why VFX Graph doesn't work with URP gamma, but can work with HDRP gamma.

Do you agree?

Edit: I am starting to wonder if HDRP is only linear argh

**Comment by keijiro** [comment]
- Linear workflow / Gamma workflow ("Color Space" in the project settings)
- Gamma texture sampling / Linear texture sampling ("sRGB"  in the texture importer settings)

These two switches are different.

HDRP only supports linear workflow.

Gamma texture sampling is only meaningful in the linear workflow.

I think VAT supports both of these workflows but you shouldn't enable gamma texture sampling when using the linear workflow.

Note: I might be wrong. I haven't touched this project for three years. I can't remember the details.
