### ISSUE TITLE
Question : How to unpack normals

### ISSUE THREAD

**Issue by NidoKota** [keijiro/HdrpVatExample#17]
I have a question about how to unpack a texture. 

https://github.com/keijiro/HdrpVatExample/blob/master/Assets/VAT/VATHelper.hlsl#L30

I am not sure what the process is for extracting the normals packed in the textures.
I have searched the internet and could not find any information on this.
Also, I could not find the source code to pack normals in the SideFX source code.
I am very sorry for the inconvenience, but could you please tell me what the process is?
Thank you in advance.

**Comment by keijiro** [comment]
I can't remember it correctly, but I think it came from the SideFX source code. You may not be able to find it in the current code set... It was 4 years ago. Many parts of it might be changed.
