### ISSUE TITLE
Possability of using this for blood?

### ISSUE THREAD

**Issue by MostHated** [keijiro/HdrpVatExample#2]
Hey there,
    This looks great! I just picked up a Houdini Indie license two weeks ago as I have been having a hard time trying to find nice looking blood effects that work for HDRP so I wanted to try to learn enough Houdini to accomplish this. I was wondering if perhaps this method you used here might be useful for that? I was going to try and use Albemic but I don't know enough about it yet, or even enough about Houdini to create liquid to try and test anything out. It would be great to get your input so I can try to steer what I am trying to learn toward whatever might end up working out best.

Thanks!
-MH

**Comment by keijiro** [comment]
There is an interesting presentation about a case using Houdini to produce blood effects.

https://www.youtube.com/watch?v=k8_6PmSKF2U

You can use the same method using the VAT shader provided within Houdini's Game Development Toolset, it only supports URP (LWRP) at the moment though.

Unfortunately, my VFX subgraph doesn't support fluid VATs (it's technically impossible), so there is nothing useful here for your case.

If you're using HDRP, I'd recommend asking SideFX for HDRP support.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
