### ISSUE TITLE
Vertex Anim Export options in Houdini 

### ISSUE THREAD

**Issue by MostHated** [keijiro/HdrpVatExample#3]
Heya,
    When I open the .hip file and look at the output vertex animation node, but then try to make one of my own, I seem to be lacking some of the options.

Here is when I click on your node:

![https://i.imgur.com/1QqJQ9F.png](https://i.imgur.com/1QqJQ9F.png)

But when I make one, I see this:

![https://i.imgur.com/dPpyoX6.png](https://i.imgur.com/dPpyoX6.png)

Are there options or a different node that I am supposed to use? I don't see the BBOX settings of anything that you used as the input within Unity.

Thanks,
-MH

**Comment by keijiro** [comment]
I used the "VAT" button in the SideFX Labs shelf. It seems that the TAB menu gives what you saw in the second screenshot. Hmm, that's very confusing. Are there multiple versions of the exporter in the same toolset? I'm not sure which one is right.

**Comment by MostHated** [comment]
Hmmm... I tried using the VAT button in the shelf as you mentioned, but I ended up with the same options in the node as I did before. I was using 18.348 (SideFX tools v348) at the time, I just opened 18.287 which had an older version of the SideFX tools (297), I ended up with the same result still if I used the tab menu or if I used the shelf. I would not think multiple version of the exporter would be in the same release, but I am not sure.

**Comment by keijiro** [comment]
I'm using 18.0.287 and SideFX Labs 299. I'll try updating it later.

**Comment by keijiro** [comment]
I confirmed that 18.0.348 gives the same result as you showed: Both the shelf and the tab menu create a node with the interface in your second screenshot.

The new exporter doesn't provide BBOX value on the parameter editor but exports runtime information to a `.json` file. Open it with a text editor and see `_posMax` and `_posMin` values. Also you can get the number of frames (`_numOfFrames`).

I'll update the document later.

**Comment by smkplus** [comment]
Hi I have same problem with houdini 17.5

![image](https://user-images.githubusercontent.com/16706911/72668672-8f03dd80-3a3e-11ea-9c00-9e39e4b35849.png)

so I tried using this node:

![image](https://user-images.githubusercontent.com/16706911/72668704-dbe7b400-3a3e-11ea-8d76-4afd7ad0ce8b.png)

but result is wrong!!!
![image](https://user-images.githubusercontent.com/16706911/72668714-f28e0b00-3a3e-11ea-9796-2022b17d1f61.png)

I also tried to use another node vertex animation experiment lab:

![image](https://user-images.githubusercontent.com/16706911/72668781-8a8bf480-3a3f-11ea-91dc-c70fd32099ad.png)


![image](https://user-images.githubusercontent.com/16706911/72755455-c78eed00-3bdf-11ea-8f8e-3c1752aad052.png)

**Comment by keijiro** [comment]
@smkplus Please try upgrading to the latest version (Houdini 18.348 and SideFX Labs v348 or later).

**Comment by MostHated** [comment]
That was the version's I was trying to use, but for some reason any time I added any time to the current time, the model would just disappear. I noticed all of yours have a relatively small range. I didn't mess with my scale really but mine ended up being -3,000 - 3000 to 4000, so perhaps I did something wrong. I think my other one I tried to do might not have worked because it was a rigid body simulation (below) and I was trying to see if I could animate it using your cloth shader.

https://i.imgur.com/f5of9rS.mp4

A week or two before I made this post, I tried to use your VFX graph for an effect I made and it was not working, but it was my first try at doing so, so I imagine it was something on my end. I literally spent an hour with your example open side by side with mine to make sure every setting was the same, all of the images import settings matched up, etc, but still nothing. As long as what outputs from Houdini currently works with what is in your example shader and VFX graph (which I am guessing it does, even with the newer sidefx tools output node)), I will just have to figure out what I am doing wrong.

**Comment by smkplus** [comment]
@keijiro 
Hi I tried with Houdini 18.0.348

I can't render vertex animation with beta version of this node
when I open your cloth.hip I have this error:
![image](https://user-images.githubusercontent.com/16706911/72752211-de7d1180-3bd6-11ea-97e4-c61bdda40c00.png)

![image](https://user-images.githubusercontent.com/16706911/72752356-39166d80-3bd7-11ea-8fd1-f07ec0b41126.png)

I tried to Install VFXToolbox but it seems it's irrelevant
https://github.com/Unity-Technologies/VFXToolbox/tree/master/DCC-Tools~/Houdini


I used GameDevelopmentToolset I wonder why didn't work!

私を助けてください 敬次郎おじさん

**Comment by smkplus** [comment]
@MostHated  MostLoved Could you fixed it?

**Comment by MostHated** [comment]
You are using Houdini v18.348, but are you using a high enough version of the SideFX Labs tools?

![https://i.imgur.com/awoFMTS.png](https://i.imgur.com/awoFMTS.png)

**Comment by smkplus** [comment]
@MostHated 
I updated it manually I have all game tools
```
HOUDINI_PATH = C:\Users\Luiz\Documents\GameDevelopmentToolset;&
PATH = C:\Users\Luiz\Documents\GameDevelopmentToolset\bin;$PATH
```

https://github.com/sideeffects/GameDevelopmentToolset

I will try it thank you

**Comment by MostHated** [comment]
That is the old repo as well, this is the new one.

https://github.com/sideeffects/SideFXLabs

**Comment by smkplus** [comment]
@MostHated 
oh thanks you should change your name to MostLoved

**Comment by keijiro** [comment]
Aha. I didn't know that the Labs repo was moved. I updated the link in README.

**Comment by smkplus** [comment]
@keijiro 
@MostHated
thank you guys I could make this possible
https://twitter.com/ShaderGuy/status/1219786869124354049?s=20

**Comment by keijiro** [comment]
I'd like to close this issue ticket for now. @MostHated Please feel free to open a new issue for further problems.
