### ISSUE TITLE
Compilation errors with Unity 2019.3.0b7

### ISSUE THREAD

**Issue by smkplus** [keijiro/HdrpVatExample#5]
I installed everythings but I have errors
I use Unity 2019.3.0b7
![image](https://user-images.githubusercontent.com/16706911/72659909-c68d6e00-39db-11ea-92b5-bb8a28395ff7.png)

![image](https://user-images.githubusercontent.com/16706911/72659896-a65daf00-39db-11ea-9b6c-a0a42b4c22f1.png)

Library\PackageCache\com.unity.render-pipelines.high-definition@7.1.7\Runtime\RenderPipeline\HDRenderPipeline.cs(652,19): error CS0117: 'SupportedRenderingFeatures' does not contain a definition for 'overridesLODBias'

Asset import failed, "Assets/Cloth/Cloth.shadergraph" > NullReferenceException: Object reference not set to an instance of an object
UnityEditor.ShaderGraph.ShaderGraphImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.shadergraph@7.1.7/Editor/Importers/ShaderGraphImporter.cs:135)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <2a08bc3d8f9c4796ba99475f6f6c6a6b>:0)

Library\PackageCache\com.unity.render-pipelines.high-definition@7.1.7\Runtime\RenderPipeline\HDRenderPipeline.cs(653,19): error CS0117: 'SupportedRenderingFeatures' does not contain a definition for 'overridesMaximumLODLevel'

**Comment by keijiro** [comment]
Could you retry with Unity 2019.3.0f5?

**Comment by smkplus** [comment]
![image](https://user-images.githubusercontent.com/16706911/72666194-252b0a00-3a25-11ea-93bb-56abf537f181.png)

it woks thanks
