### ISSUE TITLE
Low poly problem in Unity

### ISSUE THREAD

**Issue by smkplus** [keijiro/HdrpVatExample#6]
Hi I tried to use your example but something is wrong!

![image](https://user-images.githubusercontent.com/16706911/73048893-d7ccf380-3e8f-11ea-91de-a34f753918b1.png)

![Record_2020_01_24_10_03_10_319](https://user-images.githubusercontent.com/16706911/73049119-bf110d80-3e90-11ea-9b4f-e14e1a0b4920.gif)

![image](https://user-images.githubusercontent.com/16706911/73049191-06979980-3e91-11ea-8f55-b0dfb5f6bae2.png)

![image](https://user-images.githubusercontent.com/16706911/73049208-144d1f00-3e91-11ea-8f9f-b9714c2396d6.png)

oh it's because of Normals
I don't know why I couldn't export normals!

![image](https://user-images.githubusercontent.com/16706911/73049449-e2888800-3e91-11ea-8d6c-7a652d3e91c9.png)

**Comment by keijiro** [comment]
> oh it's because of Normals
> I don't know why I couldn't export normals!

Because "Pack Normals into Position Alpha" is checked in the VAT exporter settings. Try enabling "Use Packed Normals" in the material property, or just uncheck the option before exporting it.

**Comment by smkplus** [comment]
![image](https://user-images.githubusercontent.com/16706911/73050264-7a877100-3e94-11ea-8574-c0fe4baac8f4.png)

I tried to uncheck this but I haven't normal map

**Comment by keijiro** [comment]
Sorry, you also have to check "Normal" in the Paths section.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
